---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  tftpd:
    image: "registry.gitlab.com/kalaksi-containers/tftpd:1.6@sha256:41f614ba418aaba5efe1a6a3a166f66c4414f9dfcbc0b579f9dce91d667f5e0d"
    env_file: ./compose.env
    restart: unless-stopped
    ports:
      - "69:1069/udp"
    volumes:
      - "${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/volumes/tftpd/data:/tftpboot"
    # security
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    read_only: true
    cap_add:
      - CAP_SETGID
      - CAP_SETUID
      - CAP_SYS_CHROOT
