---
# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/borgmatic-collective/borgmatic/main/borgmatic/config/schema.yaml
# yamllint enable rule:line-length

# location
source_directories:
  - /mnt/volume1/docker/containers/volumes
  - /mnt/volume2/media/music/_Mix
  - /mnt/volume3/materials/books
  - /mnt/volume3/materials/magazines
  - /mnt/volume3/private
repositories:
  - path: "ssh://isx655m2@isx655m2.repo.borgbase.com/./repo"
    label: private-eu
  - path: "ssh://ls82d6e1@ls82d6e1.repo.borgbase.com/./repo"
    label: private-us

exclude_caches: true
exclude_if_present:
  - .nobackup

# directories
user_runtime_directory: /config/runtime
user_state_directory: /config/state
temporary_directory: /config/tmp
borg_base_directory: /config/borg

# storage
encryption_passphrase: "${BORGMATIC_ENCRYPTION_PASSPHRASE}"
retries: 5
compression: auto,zstd
ssh_command: ssh -i /config/ssh.key -o StrictHostKeyChecking=no
lock_wait: 5
archive_name_format: 'nas-{now:%Y-%m-%d-%H%M%S}'

# retention
keep_daily: 7
keep_weekly: 4
keep_monthly: 6
keep_yearly: 3

# consistency
checks:
  - name: repository
    frequency: "2 weeks"
  - name: archives
    frequency: always
check_last: 3

# hooks
on_error:
  - echo "`date` - Error while creating a backup."
before_backup:
  - echo "`date` - Starting backup."
after_backup:
  - echo "`date` - Finished backup."
