---
# yamllint disable rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/borgmatic-collective/borgmatic/main/borgmatic/config/schema.yaml
# yamllint enable rule:line-length

# location
source_directories:
  - /mnt/volume1/docker/containers/volumes
repositories:
  - path: /mnt/target/homelab
    label: homelab
  - path: "ssh://h3n92371@h3n92371.repo.borgbase.com/./repo"
    label: borgbase-homelab-eu
  - path: "ssh://p42wqn8z@p42wqn8z.repo.borgbase.com/./repo"
    label: borgbase-homelab-us

exclude_patterns:
  - /mnt/volume1/docker/containers/volumes/borgmatic/config/**/*
exclude_caches: true
exclude_if_present:
  - .nobackup

# directories
user_runtime_directory: /config/homelab/runtime
user_state_directory: /config/homelab/state
temporary_directory: /config/homelab/tmp
borg_base_directory: /config/homelab/borg

# storage
encryption_passphrase: "${BORGMATIC_HOMELAB_ENCRYPTION_PASSPHRASE}"
retries: 5
compression: auto,zstd
ssh_command: ssh -i /config/homelab/ssh.key -o StrictHostKeyChecking=no
lock_wait: 5
archive_name_format: 'homelab-{now:%Y-%m-%d-%H%M%S}'

# retention
keep_daily: 7
keep_weekly: 4
keep_monthly: 6
keep_yearly: 3

# consistency
checks:
  - name: repository
    frequency: "2 weeks"
  - name: archives
    frequency: always
check_last: 3

# hooks
on_error:
  - echo "`date` - Error while creating a backup."
before_backup:
  - echo "`date` - Starting backup."
after_backup:
  - echo "`date` - Finished backup."

# vim:ft=yaml
