---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  minio:
    command: "server /data --console-address :9001"
    restart: unless-stopped
    image: "quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z@sha256:3f97c5651cb6662b880c787a232b6b34fec8d8922e08d6617b25d241a21164bb"
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: ./compose.env
    networks:
      - default
      - caddy
    volumes:
      - "${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/volumes/minio/data:/data"
      - "${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/volumes/minio/secrets:/secrets"
    labels:
      caddy: "*.${ROOT_DOMAIN}"
      caddy.1_@minio: "host minio.${ROOT_DOMAIN}"
      caddy.1_handle: "@minio"
      caddy.1_handle.reverse_proxy: "{{upstreams 9001}}"
      caddy.2_@s3: "host s3.${ROOT_DOMAIN}"
      caddy.2_handle: "@s3"
      caddy.2_handle.reverse_proxy: "{{upstreams 9000}}"
    # security
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    read_only: true

networks:
  caddy:
    external: true
