---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  komodo-ferretdb:
    image: ghcr.io/ferretdb/ferretdb:1.24.1@sha256:401f0e05eced6bb07088b79db702ee0d898fdfaf28edb99b4cbe1e006733bf69
    labels:
      komodo.skip:  # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    logging:
      driver: local
    volumes:
      - ./komodo/state:/state
    environment:
      - FERRETDB_HANDLER=sqlite

  komodo-core:
    image: ghcr.io/moghtech/komodo-core:1.17.5@sha256:6471d9838695f68381c84fe4b8b9c7b303666093450158065688d9417be669eb
    labels:
      komodo.skip:  # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    depends_on:
      - komodo-ferretdb
    logging:
      driver: local
    ports:
      - 9120:9120
    env_file: ./compose.env
    environment:
      KOMODO_DATABASE_ADDRESS: ferretdb
    volumes:
      - ./komodo/repo-cache:/repo-cache
      - ./komodo/syncs:/syncs
      - ./komodo/secrets:/secrets
