[[stack]]
name = "tftpd"
[stack.config]
server = "meemee"
poll_for_updates = true
auto_update = true
repo = "ajgon/docker-gitops"
branch = "master"
reclone = true
webhook_enabled = false
run_directory = "docker/stacks/tftpd"
