[[stack]]
name = "home-assistant"
[stack.config]
server = "meemee"
auto_update = true
repo = "ajgon/docker-gitops"
branch = "master"
reclone = true
webhook_enabled = false
run_directory = "docker/stacks/home-assistant"

