---
services:
  caddy:
    image: homeall/caddy-reverse-proxy-cloudflare:2025.05.20@sha256:490e02448944faf750a4f824f521e9867fcf2b491d857d6ce7dd989190b4f6f5
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy-data:/data
    labels:
      caddy: nas.rzegocki.dev
      caddy.reverse_proxy: "http://10.100.10.1:5000"
      caddy.tls.dns: "cloudflare {env.CF_API_TOKEN}"
      caddy.tls.resolvers: "1.1.1.1"

volumes:
  caddy-data: {}
